theme: jekyll-theme-minimal
title: The Analyst Code
description: Collection of presentations for The Analyst Code
logo: https://raw.githubusercontent.com/nschmucker/Presentations/master/template/img/logo.png
show_downloads: false
